# Plotly Express (PX)

Plotly Express (PX) es la __interfaz de alto nivel__ de la biblioteca Plotly para Python. Es ideal para crear\
__gráficos interactivos__ de forma rápida y sencilla gracias a su API concisa y potente.

🧩 ¿Qué es Plotly Express?

* Es parte del módulo plotly.express, recomendado como punto de partida para generar la mayoría de los gráficos 

* Cada función de PX, como px.line(), px.bar(), px.scatter(), etc., construye un plotly.graph_objects.Figure\
internamente, pero con mucho menos código — de 5 a 100 veces más compacto que si usaras Graph Objects directamente 

* Cuenta con más de 30 tipos de visualización: gráficas de líneas, barras, tortas, mapas, 3D, distribución, etc.

✅ Beneficios de usar Plotly Express

1. Código breve y claro:

    fig = px.line(df, x='fecha', y='ventas', color='país', markers=True)

    fig.show()

    — esta línea genera un gráfico interactivo completo, elegante y funcional 

3. Interactividad por defecto:

    * Tooltip al pasar el ratón.

    * Zoom y paneo en tiempo real.

    * Posibilidad de ocultar/mostrar series clicando en la leyenda 
   
4. Estilos y defaults inteligentes:

    * Elige paletas de colores, ejes, títulos y dimensiones por defecto.

    * Permite sobrescribir fácilmente esos estilos si querés más control .

5. Integración con datos diversos:

    * Funciona con DataFrames (tidy/wide), diccionarios y arrays de NumPy.

    * También acepta Pandas, Polars, xarray, GeoPandas, etc. 

6. Modificable si necesitás más control:

    * Devuelve una Figure que podés editar con métodos como update_layout, add_trace, etc. 

Mas info en: plotly.com

In [30]:
import pandas as pd

In [7]:
# reding the csv file
df_population_raw = pd.read_csv('population_total.csv')

In [8]:
df_population_raw.head(

  country    year    population
0   China  2020.0  1.439324e+09
1   China  2019.0  1.433784e+09
2   China  2018.0  1.427648e+09
3   China  2017.0  1.421022e+09
4   China  2016.0  1.414049e+09

In [9]:
# dropping null values
df_population_raw.dropna(inplace=True)

# making pivot table
df_pivot = df_population_raw.pivot(index='year', columns='country', 
                                    values='population')

# Selecting some countries
df_pivot = df_pivot[['United States','India', 'China', 'Indonesia', 'Brazil']]

# Showing pivot table
df_pivot

country  United States         India         China    Indonesia       Brazil
year
1955.0     171685336.0  4.098806e+08  6.122416e+08   77273425.0   62533919.0
1960.0     186720571.0  4.505477e+08  6.604081e+08   87751068.0   72179226.0
1965.0     199733676.0  4.991233e+08  7.242190e+08  100267062.0   83373530.0
1970.0     209513341.0  5.551898e+08  8.276014e+08  114793178.0   95113265.0
1975.0     219081251.0  6.231029e+08  9.262409e+08  130680727.0  107216205.0
1980.0     229476354.0  6.989528e+08  1.000089e+09  147447836.0  120694009.0
1985.0     240499825.0  7.843600e+08  1.075589e+09  164982451.0  135274080.0
1990.0     252120309.0  8.732778e+08  1.176884e+09  181413402.0  149003223.0
1995.0     265163745.0  9.639226e+08  1.240921e+09  196934260.0  162019896.0
2000.0     281710909.0  1.056576e+09  1.290551e+09  211513823.0  174790340.0
2005.0     294993511.0  1.147610e+09  1.330776e+09  226289470.0  186127103.0
2010.0     309011475.0  1.234281e+09  1.368811e+09  241834215.0  195713635.0
2015.0     320878310.0  1.310152e+09  1.406848e+09  258383256.0  204471769.0
2016.0     323015995.0  1.324517e+09  1.414049e+09  261556381.0  206163053.0
2017.0     325084756.0  1.338677e+09  1.421022e+09  264650963.0  207833823.0
2018.0     327096265.0  1.352642e+09  1.427648e+09  267670543.0  209469323.0
2019.0     329064917.0  1.366418e+09  1.433784e+09  270625568.0  211049527.0
2020.0     331002651.0  1.380004e+09  1.439324e+09  273523615.0  212559417.0

# 1. Interactive Lineplot

So we will be able to see the data behind the lines.

In [33]:
import plotly.express as px

fig = px.line(df_pivot, 
              x=df_pivot.index, 
              y=df_pivot.columns,
              markers=True,
              title="Gráfico interactivo")
fig.update_layout(yaxis_title="Population")
fig.show()

In [34]:
# So this graph allows us not only to see the plot but we can see the data behind
# and we get more detail about this lineplot

# 2. Interactive Barplot

In [35]:
# Selecting only one year (2020)
df_pivot_2020 = df_pivot[df_pivot.index.isin([2020])]

# transpose dataframe from rows to columns or viceversa
df_pivot_2020 = df_pivot_2020.T

In [40]:
df_pivot_2020

year                 2020.0
country
United States  3.310027e+08
India          1.380004e+09
China          1.439324e+09
Indonesia      2.735236e+08
Brazil         2.125594e+08

In [41]:
fig = px.bar(
    df_pivot_2020,
    x=df_pivot_2020.index,  # categorías en el eje X
    y='2020.0',               # valores
    labels={'x': 'País', '2020': 'Población 2020'},
    title='Población por país en 2020',
    text='2020'            # muestra el valor sobre cada barra
)
fig.update_layout(xaxis_title='País', yaxis_title='Población 2020')
fig.show()

## 3.2 Interactive Barplot grouped by "n" variables

In [42]:
# Selecting a few years
df_pivot_sample = df_pivot[df_pivot.index.isin([1980, 1990, 2000, 2010, 2020])]
df_pivot_sample

country  United States         India         China    Indonesia       Brazil
year
1980.0     229476354.0  6.989528e+08  1.000089e+09  147447836.0  120694009.0
1990.0     252120309.0  8.732778e+08  1.176884e+09  181413402.0  149003223.0
2000.0     281710909.0  1.056576e+09  1.290551e+09  211513823.0  174790340.0
2010.0     309011475.0  1.234281e+09  1.368811e+09  241834215.0  195713635.0
2020.0     331002651.0  1.380004e+09  1.439324e+09  273523615.0  212559417.0

In [50]:
# DataFrame en formato largo
df_long = df_pivot_sample.reset_index().melt(
    id_vars='year', 
    var_name='country', 
    value_name='population'
)

fig = px.bar(
    df_long,
    x='year',
    y='population',
    color='country',         # Una barra por país
    barmode='group',         # Barras una al lado de otra
    title='Población por país a lo largo de los años',
    labels={'population': 'Población', 'year': 'Año', 'country': 'País'}
)

fig.update_layout(xaxis_title='Año', yaxis_title='Población')
fig.show()

In [47]:
# So here we have this multiple bar plots grouped by 5 variables.. and here we can
# see in detail the population of each country in the year we want.. So for example,
# India in 2020 had a population of 1.38B of inhabitants.. US in 1990 had a population
# of 252M inhabitants.

# 3. Interactive Piechart

In [51]:
# Reseteando el índice para convertir los países en columna
df_plot = df_pivot_2020.reset_index()

# Renombrando la columna de población 
df_plot = df_plot.rename(columns={2020.0: 'population'})

# Creando el gráfico de torta
fig = px.pie(
    df_plot,
    names='country',
    values='population',
    title='Proporción de población por país en 2020',
)

# Mostrar porcentaje y nombre dentro del gráfico
fig.update_traces(textinfo='percent+label')

fig.show()

# 4. Interactive Boxplot

In [52]:
# convertiendo la Serie en un DataFrame
df_us = df_pivot['United States'].reset_index()
df_us.columns = ['year', 'population']

# creando el boxplot interactivo
fig = px.box(
    df_us,
    y='population',
    points='all',  # muestra todos los puntos individuales
    title='Boxplot de la población de Estados Unidos',
    labels={'population': 'Población'},
)

fig.show()

In [53]:
# Reorganizando el DataFrame de formato ancho a largo
df_long = df_pivot.reset_index().melt(id_vars='year', 
                                      var_name='country', 
                                      value_name='population')

# Creando el boxplot
fig = px.box(
    df_long,
    x='country',
    y='population',
    points='all',  # muestra puntos individuales (opcional)
    title='Distribución de la población por país',
    labels={'country': 'País', 'population': 'Población'}
)

fig.show()

# 5. Interactive histogram

In [56]:
# Convirtiendo la Serie en DataFrame
df_us = df_pivot[['United States']].reset_index()

# Creando histograma
fig = px.histogram(
    df_us,
    x='United States',
    nbins=10,  # se puede ajustar la cantidad de bins
    title='Histograma de la población de Estados Unidos',
    labels={'United States': 'Población'}
)

fig.show()

In [57]:
# the first interval has 1 value, the 2nd and 3rd interval have 2 values, ..., the last interval has 6 values

In [60]:
# Convirtiendo de formato ancho a largo
df_hist = df_pivot[['United States', 'Indonesia']].reset_index().melt(
    id_vars='year',
    var_name='country',
    value_name='population'
)

# Creando histogramas interactivos con colores por país
fig = px.histogram(
    df_hist,
    x='population',
    color='country',
    nbins=15,
    barmode='overlay',  # usa 'group' si querés verlos lado a lado
    title='Histograma de población: Estados Unidos vs Indonesia',
    labels={'population': 'Población'}
)

fig.show()

In [61]:
# se puede clickear en la leyenda el pais que queramos y solo mostrará el histograma asociado a ese pais.

# 6. ScatterPlot

In [65]:
df_pivot.head()

country  United States        India        China    Indonesia       Brazil
year
1955.0     171685336.0  409880595.0  612241554.0   77273425.0   62533919.0
1960.0     186720571.0  450547679.0  660408056.0   87751068.0   72179226.0
1965.0     199733676.0  499123324.0  724218968.0  100267062.0   83373530.0
1970.0     209513341.0  555189792.0  827601394.0  114793178.0   95113265.0
1975.0     219081251.0  623102897.0  926240885.0  130680727.0  107216205.0

In [66]:
# df_pivot tiene años como índice y países como columnas
df_long = df_pivot.reset_index().melt(id_vars='year', var_name='País', value_name='Población')

# Creando el scatter plot
fig = px.scatter(
    df_long,
    x='year',
    y='Población',
    color='País',
    title='Población por país a lo largo del tiempo (Scatter Plot)',
    labels={'year': 'Año'}
)

fig.show()

In [67]:
# now if we select any dot, we will see in detail the value behind a dot.. So for example, China in 1985
# had a population of 1.075B inhabitants.. And we can see all the values behind all the dots in this ScatterPlot.

In [68]:
# And that's how interactive visualizations can be made with Pandas.