In [1]:
import pandas as pd

## 1.3 Exclusive Full join

Exclusive full joins will pick only the values that are exclusive to the table (it's the complement of\
the intersection between two sets. That is: all the elements that belong to the table 1 and table 2 except\
the elements that they have in common).

So here I have two tables, and the exclusive values from table 1 and the exclusive values from table 2\
will be taken in this exclusive full join.

We have to find a column in common, a column that both dataframes have. And to make this full join we have\
to use the merge() method:

df1.merge(df2, on='id', how='outer', indicator=True)

So this indicator helps us known which values are exlusive to df1 and which values are exlusive to df2.\
After we add this indicator, we're going to get a new column in our output dataframe. And this column is\
going to be named _merge, and in this column we're going to see values like left only, right only and both.

So the values that are left only corresponds only to the dataframe on the left, in this case df1.\
And the values that say right only corresponds only to the dataframe on the right, which is df2.\
And this are the values that are exclusive to df1 and df2.

Once we have this _merge column, we're going to use the query() method to select only the exclusive values\
to df1 and exclusive values to df2. And with this, we're going to filter out the values that this two dfs\
have in common.

In [2]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'id': ['C', 'D', 'E', 'F'],
                    'job': ['Doctor', 'Statistician', 
                            'Engineer', 'Developer']})

In [3]:
df1

  id  age
0  A   30
1  B   23
2  C   25
3  D   22

In [4]:
df2

  id           job
0  C        Doctor
1  D  Statistician
2  E      Engineer
3  F     Developer

In [6]:
# full join
df1.merge(df2, on='id', how='outer')

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN      Engineer
5  F   NaN     Developer

In [5]:
# indicator=True
df1.merge(df2, on='id', how='outer', indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN      Engineer  right_only
5  F   NaN     Developer  right_only

In [7]:
# i'm going to select only the values that are exclusive to df1 (left_only)
# and exclusive to df2 (right only)

In [8]:
# query
df1.merge(df2, on='id', how='outer', 
          indicator=True).query("_merge=='left_only' or _merge=='right_only'")

  id   age        job      _merge
0  A  30.0        NaN   left_only
1  B  23.0        NaN   left_only
4  E   NaN   Engineer  right_only
5  F   NaN  Developer  right_only

In [9]:
# and now we can see, that this df that we have as output only show the values
# that are left_only and right_only.

# And that's everything we have to do to make an exclusive full join.

In [10]:
# shape
print(df1.shape)
print(df2.shape)
print(df1.merge(df2, on='id', how='outer',
          indicator=True).query("_merge=='left_only' or _merge=='right_only'").shape)

(4, 2)
(4, 2)
(4, 4)

## Example

In [11]:
# merging df_movies and df_ratings

In [12]:
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv', low_memory=False)

In [13]:
# selecting the columns
df_movies = df_movies[['imdb_title_id', 'title', 'year', 
                       'genre', 'country']]
df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]
# both dfs have in common the column imdb_title_id

In [14]:
df_movies.merge(df_ratings, on='imdb_title_id', how='outer',
            indicator=True).query("_merge=='left_only' or _merge=='right_only'")

Empty DataFrame
Columns: [imdb_title_id, title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

In [15]:
# and we see that this df is empty, that is because all the elements in df1 and df2 
# belong to both dataframes..  all the values in the id column are the same 
# betweent the df_movies and the df_ratings. So this two dfs have the same ids.
# And non of this dataframes have exclusive id. So this is why we got this empty df,
# because these two df don't have exclusive values.

In [16]:
# but the code that has the merge() method is correct.

In [17]:
# And that's how exclusive full join can be made.